services:
  mlsgpt-arm64:
    container_name: mlsgpt-arm64
    image: mlsgpt-arm64/python3.12:latest
    networks:
      - mlsgpt
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./.env.deploy:/app/.env:ro
    ports:
      - 80:80

networks:
  mlsgpt:
    driver: bridge
