services:
  mlsgpt-arm64:
    container_name: mlsgpt-arm64
    image: kwesi/mlsgpt-arm64:latest
    networks:
      - mlsgpt
    volumes:
      - ./.env.deploy:/app/.env:ro
    ports:
      - 80:80

networks:
  mlsgpt:
    driver: bridge
