name: Build and Deploy MLSGPT
on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
      - release/*
      - bugfix/*
      - fix/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlsgpt-amd64:latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy via SSH"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker-compose stop | true
            docker-compose rm -f | true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mlsgpt-amd64:latest
            docker-compose up -d
